name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there welcome to Eazy5D page, Thanks for visiting.s'' first issue'
        pr-message: 'Thanks for visiting my page'' first pr'
